# Generated by Django 4.0.4 on 2022-05-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemObject',
            new_name='Task',
        ),
    ]
