# Generated by Django 4.0.4 on 2022-05-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_rename_itemobject_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomModel',
            new_name='CustomUser',
        ),
    ]
